name: Python Tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: docker build -t mixmasta .

      - name: Run tests
        run: docker run -w=/tests --entrypoint="python3" mixmasta -m unittest test_mixmasta.py -v

